query userInfo($login: String!, $after: String = null, $startTime: DateTime) {
  user(login: $login) {
    name
    avatarUrl
    contributions: contributionsCollection(from: $startTime) {
      totalCommitContributions
      totalPullRequestReviewContributions
      totalRepositoryContributions
      totalIssueContributions
    }
    pullRequests {
      totalCount
    }
    mergedPRs: pullRequests(states: MERGED) {
      totalCount
    }
    openIssues: issues(states: OPEN) {
      totalCount
    }
    closedIssues: issues(states: CLOSED) {
      totalCount
    }
    repositories(
      ownerAffiliations: OWNER
      orderBy: {field: STARGAZERS, direction: DESC}
      first: 100
      isFork: false
      after: $after
    ) {
      totalCount
      nodes {
        stargazerCount
      }
      pageInfo {
        hasNextPage
        endCursor
      }
    }
  }
}
